version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customers
    volumes:
      - ./init-data:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
